FROM bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8

USER root

# Install Python and dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Set python3 as default
RUN ln -s /usr/bin/python3 /usr/bin/python || true

# Install FastAPI dependencies and mrjob
RUN pip3 install --no-cache-dir fastapi==0.111.0 uvicorn[standard]==0.30.1 python-multipart==0.0.9

WORKDIR /app

ENV PYTHONPATH="${PYTHONPATH}:/app"

# Command to run FastAPI
CMD ["uvicorn", "deployment.app:app", "--host", "0.0.0.0", "--port", "8000"]
